(ns immersa.scene.api.assets)

(def assets
  {:texts #{"shader/nme/purpleGlass.json"
            "shader/nme/sphere_stone.json"
            "shader/nme/sphere_world.json"
            "shader/nme/translucent.json"
            "shader/nme/nebula.json"}
   :cube-textures #{"img/skybox/sunny/sunny"
                    "img/skybox/space/space"
                    "img/skybox/black/black"
                    "img/skybox/background/background"
                    "img/texture/environment/environmentSpecular.env"
                    "img/texture/environment/cube_specular.env"
                    "img/texture/skybox/backgroundSkybox.dds"}
   :textures #{"img/texture/noise/ac.jpg"
               "img/texture/numbers.jpg"
               "img/texture/pp.jpeg"
               "img/texture/flare.png"
               "img/texture/2d-slide.png"
               "img/texture/gg.png"
               "img/texture/fire_01.png"
               "img/texture/star_04.png"
               "img/texture/star_08.png"
               "img/texture/smoke_01.png"
               "img/texture/earth/diffuse2-min.png"
               "img/texture/earth/emmisive.jpeg"
               "img/texture/earth/specular.jpeg"
               "img/texture/earth/bump.jpeg"
               "img/texture/earth/clouds2-min.jpg"
               "img/texture/ground/backgroundGround.png"
               "img/texture/copper-diffuse.png"
               "img/texture/copper-normal.jpg"
               "img/texture/clouds.png"
               "img/texture/sphere_stone_1.png"
               "img/texture/sphere_stone_2.png"
               "img/texture/sphere_stone_3.png"
               "img/texture/sphere_stone_4.png"}
   :models #{"model/plane_2.glb"
             "model/porche_911.glb"}})
